services:

  postgres:
    image: postgres:16
    container_name: oldworldbazaar-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: oldworldbazaar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile.dev

    container_name: oldworldbazaar-backend

    depends_on:
      - postgres

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=oldworldbazaar;Username=postgres;Password=postgres

    ports:
      - "5194:5194"

    volumes:
      - ./backend:/src

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.dev

    container_name: oldworldbazaar-frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: